"""Rename 'is_active' to 'status' in User model

Revision ID: 10d571bf5fea
Revises: ea271267ecd7
Create Date: 2026-02-14 15:20:08.026862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '10d571bf5fea'
down_revision: Union[str, None] = 'ea271267ecd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


status_type_enum = ENUM(
    'active', 'blocked',
    name='userstatusenum'
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ##
    status_type_enum.create(op.get_bind())
    op.add_column('user', sa.Column('status', status_type_enum, comment='Status of user'))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Status of user'))
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
