"""Added 'role' in User model

Revision ID: 28272990b7c9
Revises: 42e13ab23ec7
Create Date: 2026-02-20 13:00:03.723909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28272990b7c9'
down_revision: Union[str, None] = '42e13ab23ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Товары в заказе',
               existing_nullable=True)
    op.add_column('user', sa.Column('role', sa.Enum('admin', name='user_role_enum'), nullable=True, comment='Role of user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.alter_column('order', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Товары в заказе',
               existing_nullable=True)
    # ### end Alembic commands ###
