"""Remoed 'nullable=True' from 'items' in 'Order' model

Revision ID: 2d5d797330b0
Revises: e58c31efcbee
Create Date: 2026-02-11 13:38:02.406240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d5d797330b0'
down_revision: Union[str, None] = 'e58c31efcbee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_comment='Товары в заказе')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_comment='Товары в заказе')
    # ### end Alembic commands ###
