"""Updated 'status' in User model

Revision ID: 42e13ab23ec7
Revises: 10d571bf5fea
Create Date: 2026-02-14 15:49:08.630172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42e13ab23ec7'
down_revision: Union[str, None] = '10d571bf5fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=postgresql.ENUM('active', 'blocked', name='userstatusenum'),
               nullable=False,
               existing_comment='Status of user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=postgresql.ENUM('active', 'blocked', name='userstatusenum'),
               nullable=True,
               existing_comment='Status of user')
    # ### end Alembic commands ###
