"""Added 'items' in 'Order' model

Revision ID: e58c31efcbee
Revises: 96b68ceaf4d8
Create Date: 2026-02-11 13:36:39.324820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e58c31efcbee'
down_revision: Union[str, None] = '96b68ceaf4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Товары в '
                                                                                                           'заказе'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'items')
    # ### end Alembic commands ###
