"""Added 'is_active' in User model

Revision ID: ea271267ecd7
Revises: 2d5d797330b0
Create Date: 2026-02-14 15:09:19.082678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = 'ea271267ecd7'
down_revision: Union[str, None] = '2d5d797330b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True, comment='Status of user'))
    op.execute(text("UPDATE \"user\" SET is_active = true WHERE is_active IS NULL"))
    op.alter_column('user', 'is_active', nullable=False, comment='Status of user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
